version: '3'

services:
  app:
    build: .
    restart: always
    volumes:
      - build:/app/dist

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - 3000:80
    volumes:
      - ./config/nginx/servers/:/etc/nginx/conf.d/
      - build:/app/dist

volumes:
  build:
